import React, { useEffect, useState, useMemo, useRef } from 'react';
import { useApp } from '../context/AppContext';
import { fetchReports, fetchReportExport, isMedusaCatalogueEnabled } from '../catalogue/catalogueClient';
import { downloadCsv, dateStamp } from '../utils/exportCsv';
import { MOCK_DEPARTMENT_CONSUMPTION, CAGELI_PRODUCTS } from '../data/mockData';
import { LiveReportBuilder } from './LiveReportBuilder';
import { AuditLogCard } from './AuditLogCard';
import {
  TrendingUp, AlertTriangle, FileDown, Boxes, Wallet, TriangleAlert, PackageX,
  Users, HardHat, Building2, Layers, Loader2, ShieldCheck
} from 'lucide-react';

export const InventoryAnalyticsPortal = () => {
  const { products, activePlant, auth, tenantAccess, triggerNotification } = useApp();
  const scope = { accessToken: auth?.session?.access_token, tenantId: tenantAccess?.activeTenantId, siteId: tenantAccess?.activeSiteId };
  const live = isMedusaCatalogueEnabled && !!scope.accessToken && !!scope.tenantId;
  const canRunReports = (tenantAccess?.capabilities ?? []).includes('reports.run');

  // Export a server-authoritative stock report to send to the mine. reports.run
  // is MFA-gated, so if the session is aal1 we prompt the authenticator step-up
  // and retry the export once elevated.
  const [exporting, setExporting] = useState(null); // 'csv' | 'pdf' | null
  const pendingExportRef = useRef(null);

  const zar = (n) => `R ${Number(n || 0).toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const esc = (v) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const exportCsv = (r) => {
    const cols = [
      { key: 'sku', label: 'SKU' }, { key: 'name', label: 'Item' }, { key: 'category', label: 'Category' },
      { key: 'onHand', label: 'On hand' }, { key: 'inTransit', label: 'In transit' },
      { key: 'unitCost', label: 'Unit cost' }, { key: 'unitPrice', label: 'Unit price (RP)' },
      { key: 'stockCost', label: 'Stock cost value' }, { key: 'stockRetail', label: 'Stock value (RP)' },
      { key: 'coverDays', label: 'Cover (days)' },
    ];
    downloadCsv(`stock-report-${dateStamp()}`, cols, r.rows ?? []);
  };

  const exportPdf = (r) => {
    const w = window.open('', '_blank');
    if (!w) { triggerNotification('Popup blocked', 'Allow popups to open the PDF report.', 'warning'); return; }
    const rows = r.rows ?? [];
    const totCost = rows.reduce((a, x) => a + Number(x.stockCost || 0), 0);
    const totRetail = rows.reduce((a, x) => a + Number(x.stockRetail || 0), 0);
    const gen = String(r.generatedAt || new Date().toISOString()).slice(0, 16).replace('T', ' ');
    const body = rows.map((x) => `<tr>
      <td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td class="mut">${esc(x.category)}</td>
      <td class="n">${x.onHand ?? 0}</td><td class="n mut">+${x.inTransit ?? 0}</td>
      <td class="n">${zar(x.unitCost)}</td><td class="n">${zar(x.unitPrice)}</td>
      <td class="n b">${zar(x.stockRetail)}</td><td class="n ${x.coverDays != null && x.coverDays < 14 ? 'lo' : ''}">${x.coverDays == null ? '—' : x.coverDays + 'd'}</td>
    </tr>`).join('');
    w.document.write(`<html><head><title>Stock Report ${dateStamp()} — SightLive</title><style>
      body{font-family:Inter,Arial,sans-serif;color:#111;padding:30px;font-size:12px}
      .row{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #111;padding-bottom:14px;margin-bottom:16px}
      h1{font-size:20px;margin:0}.brand{font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#ef5b0a;margin-top:4px}
      .mut{color:#666}table{width:100%;border-collapse:collapse;margin-top:8px}
      th,td{padding:6px 8px;border-bottom:1px solid #ddd}th{background:#f5f5f4;text-transform:uppercase;font-size:9px;letter-spacing:.05em;text-align:left;color:#555}
      td.n,th.n{text-align:right}td.b{font-weight:700}td.lo{color:#c0392b;font-weight:600}
      tfoot td{font-weight:700;border-top:2px solid #999;background:#fafafa}
      .meta{text-align:right;font-size:11px;color:#666;line-height:1.6}
    </style></head><body>
      <div class="row">
        <div><h1>Stock Report</h1><div class="brand">SightLive · CageLi PPE</div></div>
        <div class="meta">Generated ${esc(gen)}<br/>Currency: ${esc(r.currency || 'ZAR')}<br/>${rows.length} SKUs</div>
      </div>
      <table>
        <thead><tr><th>SKU</th><th>Item</th><th>Category</th><th class="n">On hand</th><th class="n">Transit</th><th class="n">Unit cost</th><th class="n">Unit price</th><th class="n">Stock value (RP)</th><th class="n">Cover</th></tr></thead>
        <tbody>${body}</tbody>
        <tfoot><tr><td colspan="7">Totals</td><td class="n">${zar(totRetail)}</td><td class="n mut">cost ${zar(totCost)}</td></tr></tfoot>
      </table>
      <p class="mut" style="margin-top:18px;font-size:10.5px">Stock valuation at retail (RP). Cover = (on hand + in transit) ÷ daily consumption. Generated by the SightLive PPE platform to report stock position to the mine.</p>
    </body></html>`);
    w.document.close(); w.focus(); setTimeout(() => w.print(), 350);
  };

  const runExport = async (format = 'csv') => {
    if (!live) { triggerNotification('Not connected', 'Report export needs the live backend.', 'info'); return; }
    setExporting(format);
    try {
      const r = await fetchReportExport(scope);
      if (format === 'pdf') exportPdf(r); else exportCsv(r);
      triggerNotification('Report exported', `Stock report (${(r.rows ?? []).length} SKUs) — ready to send to the mine.`, 'success');
    } catch (e) {
      if (e?.code === 'mfa_required') {
        pendingExportRef.current = format;
        if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent('sightlive:mfa-required'));
        triggerNotification('Verify to export', 'Confirm with your authenticator to run the report.', 'info');
      } else {
        triggerNotification('Export failed', e?.message || 'Could not generate the report.', 'danger');
      }
    } finally { setExporting(null); }
  };
  // Retry the pending export automatically once the session is elevated.
  useEffect(() => {
    const h = () => { const f = pendingExportRef.current; if (f) { pendingExportRef.current = null; runExport(f); } };
    window.addEventListener('sightlive:mfa-elevated', h);
    return () => window.removeEventListener('sightlive:mfa-elevated', h);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [live, scope.accessToken, scope.tenantId]);

  // Live tenant reports (stock valuation + reorder)
  const [reports, setReports] = useState(null);
  useEffect(() => {
    if (!live) { setReports(null); return; }
    let active = true;
    fetchReports(scope).then((r) => { if (active) setReports(r.reports ?? null); }).catch(() => { if (active) setReports(null); });
    return () => { active = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [live, scope.accessToken, scope.tenantId, scope.siteId]);

  const getItemPrice = (p) => {
    if (p.sellingPrice != null && !isNaN(Number(p.sellingPrice)) && Number(p.sellingPrice) > 0) return Number(p.sellingPrice);
    const mock = CAGELI_PRODUCTS.find((cp) => cp.sku === p.sku);
    return mock?.sellingPrice || 0;
  };

  // Stock valuation to the mine is based on the Retail Price (the billed asset value).
  const stockValue = reports?.stockValuation?.totals?.stockRetailValue != null
    ? reports.stockValuation.totals.stockRetailValue
    : products.reduce((a, p) => a + getItemPrice(p) * (p.stockOnHand ?? 0), 0);

  const cover = (p) => Math.round(((p.stockOnHand || 0) + (p.stockInTransit || 0)) / (p.dailyConsumption || 1));
  const belowMin = reports?.reorder?.rows?.length != null
    ? reports.reorder.rows
    : products.filter((p) => cover(p) < 14);
  const critical = (reports?.reorder?.rows ?? products.filter((p) => cover(p) < 8)).length;
  const maxDept = Math.max(...MOCK_DEPARTMENT_CONSUMPTION.map((c) => c.vsEntitle));

  const FLAGS = [
    { t: 'Engineering & Maintenance: 168% entitlement consumption', open: true },
    { t: 'Store 2: 14 issues logged after shift end', open: true },
    { t: 'Heavy Nitrile Gloves: consumption 3× site average', open: true },
    { t: '1 approver signs 92% of early-replacement exceptions', open: true },
  ];

  const KPIS = [
    { icon: Wallet, label: 'Mine stock value (@ RP)', value: `R ${(stockValue / 1e6).toFixed(2)}m`, sub: live ? 'live plant inventory' : 'across all plant stores' },
    { icon: Building2, label: 'Monthly mine spend', value: 'R 223.6k', sub: 'across 6 departments', cls: 'up' },
    { icon: TriangleAlert, label: 'Quota flags', value: '2 departments', sub: 'exceeding 100% entitlement', accent: true },
    { icon: PackageX, label: 'Below min stock', value: `${belowMin.length} items`, sub: `${critical} critical cover` },
  ];

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: 22, paddingBottom: 24 }}>
      <div className="page-head">
        <div>
          <h2>{activePlant.name} — PPE Control &amp; Allocation</h2>
          <p>Mine stock valuation, departmental consumption against entitlement, and employee issue registers.</p>
        </div>
        {canRunReports && (
          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-primary" onClick={() => runExport('pdf')} disabled={!!exporting} title="Stock report as a printable PDF to send to the mine">
              {exporting === 'pdf' ? <><Loader2 size={16} className="spin" /> Exporting…</> : <><FileDown size={16} /> Export PDF</>}
            </button>
            <button className="btn btn-secondary" onClick={() => runExport('csv')} disabled={!!exporting} title="Stock report as a CSV spreadsheet">
              {exporting === 'csv' ? <><Loader2 size={16} className="spin" /> …</> : <>CSV</>}
            </button>
          </div>
        )}
      </div>

      {/* KPIs */}
      <div className="cols cols-4">
        {KPIS.map((k) => {
          const Icon = k.icon;
          return (
            <div key={k.label} className="card" style={{ borderColor: k.accent ? 'var(--primary-weak-bd)' : 'var(--border)' }}>
              <div className="card-bd" style={{ padding: 16 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <span className="kpi-label">{k.label}</span>
                  <Icon size={18} style={{ color: k.accent ? 'var(--primary)' : 'var(--text-subtle)' }} />
                </div>
                <div className="kpi-value" style={{ color: k.accent ? 'var(--primary)' : 'var(--text)' }}>{k.value}</div>
                <div className={`kpi-sub ${k.cls || ''}`}>{k.sub}</div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Department Consumption & Flags */}
      <div className="cols" style={{ gridTemplateColumns: '1.4fr 1fr' }}>
        <div className="card">
          <div className="card-hd">
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Layers size={17} style={{ color: 'var(--primary)' }} />
              <h3>Consumption per department vs entitlement</h3>
            </div>
            <span className="badge badge-neutral">this month</span>
          </div>
          <div className="card-bd">
            <div style={{ display: 'flex', alignItems: 'flex-end', gap: 12, height: 150, borderBottom: '1px solid var(--border)', paddingBottom: 2 }}>
              {MOCK_DEPARTMENT_CONSUMPTION.map((c) => (
                <div key={c.dept} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', height: '100%' }}>
                  <span style={{ fontSize: 11, fontWeight: 600, color: c.flag ? 'var(--primary)' : 'var(--text-muted)', marginBottom: 4 }}>
                    {c.vsEntitle}%
                  </span>
                  <div style={{ width: '100%', maxWidth: 38, height: `${(c.vsEntitle / maxDept) * 100}%`, background: c.flag ? 'var(--primary)' : 'var(--surface-3)', borderRadius: '6px 6px 0 0' }} />
                </div>
              ))}
            </div>
            <div style={{ display: 'flex', gap: 12, marginTop: 8 }}>
              {MOCK_DEPARTMENT_CONSUMPTION.map((c) => (
                <span key={c.dept} style={{ flex: 1, textAlign: 'center', fontSize: 11, color: c.flag ? 'var(--primary)' : 'var(--text-muted)', fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={c.dept}>
                  {c.dept.split(' ')[0]}
                </span>
              ))}
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginTop: 14, fontSize: 13, color: 'var(--primary)', fontWeight: 500 }}>
              <AlertTriangle size={15} /> Engineering &amp; Maintenance at 168% of entitlement — 3 months running.
            </div>
          </div>
        </div>

        <div className="card">
          <div className="card-hd"><h3>Flags to review</h3><span className="badge badge-danger">{FLAGS.filter((f) => f.open).length} open</span></div>
          <div className="card-bd" style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
            {FLAGS.map((f, i) => (
              <div key={i} className="card" style={{ boxShadow: 'none', background: f.open ? 'var(--danger-weak)' : 'var(--surface-2)', borderColor: f.open ? 'var(--primary-weak-bd)' : 'var(--border)' }}>
                <div className="card-bd" style={{ padding: '11px 13px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8 }}>
                  <span style={{ fontSize: 13 }}>{f.t}</span>
                  {f.open && <span className="badge badge-danger" style={{ fontSize: 10 }}>open</span>}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Full tenant reports — stock allocation, valuation, reorder, spend, orders
          (CSV + Print/PDF per report), so a merchant can report PPE to the mine. */}
      <LiveReportBuilder scope={scope} triggerNotification={triggerNotification} />

      {/* Stock ledger */}
      <div className="card">
        <div className="card-hd">
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Boxes size={17} style={{ color: 'var(--primary)' }} />
            <h3>Stock ledger — forward cover &amp; valuation</h3>
          </div>
          <span className={`badge ${live ? 'badge-success' : 'badge-neutral'}`}>{live ? `${products.length} live SKUs` : `${products.length} SKUs`}</span>
        </div>
        {live && products.length === 0 && (
          <div className="card-bd muted" style={{ padding: 20, fontSize: 13.5 }}>Connecting to the live catalogue… stock will appear here once the tenant link resolves.</div>
        )}
        {products.length > 0 && (
          <div className="table-wrap">
            <table className="table">
              <thead>
                <tr>
                  <th>SKU</th>
                  <th>Item description</th>
                  <th>Department / Category</th>
                  <th className="num">Unit price (RP)</th>
                  <th className="num">On hand</th>
                  <th className="num">Transit</th>
                  <th className="num">Total value (RP)</th>
                  <th className="num">Cover</th>
                </tr>
              </thead>
              <tbody>
                {products.map((p) => {
                  const cv = cover(p);
                  const low = cv < 14;
                  const price = getItemPrice(p);
                  const lineTotal = price * (p.stockOnHand || 0);
                  return (
                    <tr key={p.sku} className={low ? 'row-flag' : ''}>
                      <td className="muted" style={{ fontWeight: 500 }}>{p.sku}</td>
                      <td style={{ fontWeight: 600 }}>{p.name}</td>
                      <td className="muted">{p.category || 'General PPE'}</td>
                      <td className="num tabular">R {price.toFixed(2)}</td>
                      <td className="num tabular">{p.stockOnHand ?? 0}</td>
                      <td className="num tabular muted">+{p.stockInTransit ?? 0}</td>
                      <td className="num tabular" style={{ fontWeight: 600 }}>R {lineTotal.toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
                      <td className="num tabular" style={{ color: low ? 'var(--danger)' : 'var(--text)', fontWeight: low ? 600 : 400 }}>{cv}d</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Tenant audit trail — for roles with audit.read (e.g. merchant reporting
          PPE stock activity to the mine). MFA-gated with an authenticator step-up. */}
      {(tenantAccess?.capabilities ?? []).includes('audit.read') && <AuditLogCard />}
    </div>
  );
};
